version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
